### PR TITLE
cffi: minor fixes/improvements

### PR DESCRIPTION
**Pull request by rtobar**
Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>

### CODE REVIEW

**Comment by isagalaev** [comment]
Took me long enough… Thanks for the contribution!

**Comment by rolando** [comment]
Would be possible to have a release with this bug fixes?

I'm trying to use the library with Python 3.6 and YAJL 2.1 and get the variadic error message.

**Comment by isagalaev** [comment]
I actually hope to get to it within a week. There's another pure-C backend in a PR nearby, and I wanted to get that in shape for the next release as well.

**Comment by rolando** [comment]
That would be great!

**Pull request merged**
